### ISSUE TITLE
I'm getting this error message. I've gotten it twice now and managed to update the order id.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/opencart#18]
![web payment](https://cloud.githubusercontent.com/assets/10434920/6041155/e9ac34ec-ac79-11e4-939b-16412a6d356b.png)

**Comment by andyjohansson** [comment]
This could be a outside bug that is not related to the module in test mode.

**Comment by Boxedsolutions** [comment]
Its not really a bug, because of our opencart account has probably a order_id 20 with bankpayment. In a real account this may happen if lets say a customer has 2 opencart installations pointing to the same Billmate Account.

But I wonder if we are in need of appending timestamp to order_id? Its a way to get every order id unique.

**Comment by andyjohansson** [comment]
Not if the order id is consequent all the time.

**Comment by joakim-combain** [comment]
It seems like I have found how to recreate this. When I choose bank and then cancel in payment window. Now it will not allow me to continue no matter how many times I update the order id by refreshing the page.

**Comment by Boxedsolutions** [comment]
Hmm.. Seems to me like it is some bug on d2i. If you go to the bank payment window and cancel payment, it would be reasonable that the bank payment window resets the order number for the canceled payment?

**Comment by andyjohansson** [comment]
I will bring this up with them, this is not a plugin issue.
